Repository FrederikTobner/tobot-engine, pull requests merged in 2023-05, with the labels that each got.

#76 Editor cleanup
  BuildFromSource.md
  editor/CMakeLists.txt
  editor/color_picker.cpp
  editor/color_picker.hpp
  editor/dockspace.cpp
  editor/dockspace.hpp
  editor/event_handler.cpp
  editor/event_handler.hpp
  editor/main.cpp
  editor/menu_bar.cpp
  editor/menu_bar.hpp
  editor/scene_renderer.cpp
  editor/scene_renderer.hpp
  editor/toolbar.cpp
  editor/toolbar.hpp
  packages/tobot_io/src/pre_compiled_header.hpp
  scripts/README.md
  scripts/build.lua
  scripts/format.lua
  scripts/install_dependencies.lua
Labels: enhancement, code-quality

#75 hbl: added simple implementation of a directed graph and some tests f…
  packages/tobot_data_structures/src/CMakeLists.txt
  packages/tobot_data_structures/src/graph/directed_graph.hpp
  packages/tobot_data_structures/src/include/tobot_data_structures.hpp
  packages/tobot_data_structures/src/pre_compiled_header.hpp
  packages/tobot_data_structures/test/CMakeLists.txt
  packages/tobot_data_structures/test/directed_graph_test.cpp
Labels: enhancement

#78 Core improvements and implemented rotation
  CONTRIBUTING.md
  example/assets/Player_Gold.png
  example/assets/Weapon_Parazoinium.png
  example/src/CMakeLists.txt
  example/src/example.cpp
  packages/tobot_core/src/CMakeLists.txt
  packages/tobot_core/src/game_entity.cpp
  packages/tobot_core/src/game_entity.hpp
  packages/tobot_core/src/render_object.cpp
  packages/tobot_core/src/render_object.hpp
  packages/tobot_core/src/scene.cpp
  packages/tobot_core/src/scene.hpp
  packages/tobot_core/src/string_hash.cpp
  packages/tobot_core/src/string_hash.hpp
  packages/tobot_core/src/tobot_application.cpp
  packages/tobot_core/src/tobot_application.hpp
  packages/tobot_core/src/tobot_texture.cpp
  packages/tobot_core/src/tobot_texture.hpp
  packages/tobot_core/src/transform2D.cpp
  packages/tobot_core/src/transform2D.hpp
Labels: code-quality
