Repository FrederikTobner/tobot-engine, pull requests merged in 2023-03, with the labels that each got.

#18 feat: :sparkles: Made tobot.h possible and logger improvements
  example/example.cpp
  src/tobot.h
  src/utilities/logger.cpp
  src/utilities/logger.h
Labels: enhancement

#20 ci: Added code analysis
  .github/workflows/codeql.yaml
Labels: enhancement

#22 ci: improved workflows
  .github/workflows/build.yaml
  .github/workflows/codeql.yaml
Labels: automation

#23 feat: :sparkles: sdl initializer
  example/CMakeLists.txt
  src/CMakeLists.txt
  src/core/tobot_application.cpp
  src/core/tobot_application.h
  src/entry_point.h
  src/include/tobot.h
  src/tobot.h
Labels: enhancement

#24 feat: Scenes and GameEntities
  .vscode/settings.json
  CMakeLists.txt
  example/example.cpp
  src/CMakeLists.txt
  src/core/asset_manager.cpp
  src/core/asset_manager.h
  src/core/game_entity.cpp
  src/core/game_entity.h
  src/core/render_object.cpp
  src/core/render_object.h
  src/core/scene.cpp
  src/core/scene.h
  src/core/tobot_application.cpp
  src/core/tobot_application.h
  src/core/view.cpp
  src/core/view.h
  src/include/tobot.h
  src/math/vector2d.h
  src/utilities/concepts.h
Labels: documentation, enhancement

#29 ci: Add test workflow
  .github/workflows/codeql.yaml
  .github/workflows/tests.yaml
Labels: automation

#28 style: :art: added coding style using clang-format
  .clang-format
  .vscode/settings.json
  example/example.cpp
  src/core/asset_manager.cpp
  src/core/asset_manager.h
  src/core/game_entity.cpp
  src/core/game_entity.h
  src/core/render_object.cpp
  src/core/render_object.h
  src/core/scene.cpp
  src/core/scene.h
  src/core/tobot_application.cpp
  src/core/tobot_application.h
  src/entry_point.h
  src/include/tobot.h
  src/math/vector2d.h
  src/utilities/concepts.h
  src/utilities/logger.h
  src/utilities/tobot_asserts.h
  src/widget/text.h
  tests/main.cpp
  tests/math/vector2d_test.cpp
Labels: code-quality

#32 feat: :boom: Added SceneManager, clang format script and refactoring
  .clang-format
  .vscode/launch.json
  CMakeLists.txt
  example/example.cpp
  scripts/format.bat
  src/CMakeLists.txt
  src/core/asset_manager.h
  src/core/game_entity.cpp
  src/core/game_entity.h
  src/core/render_object.h
  src/core/scene.cpp
  src/core/scene.h
  src/core/scene_manager.h
  src/core/tobot_application.cpp
  src/core/tobot_application.h
  src/include/tobot.h
  src/math/dimension.h
  src/math/vector2d.h
  src/utilities/concepts.h
  src/utilities/logger.h
  src/widget/text.h
  tests/CMakeLists.txt
Labels: enhancement

#34 feat: :fire: added tobot_tooling
  .vscode/launch.json
  .vscode/settings.json
  CMakeLists.txt
  README.md
  example/CMakeLists.txt
  example/example.cpp
  packages/CMakeLists.txt
  packages/tobot_engine/CMakeLists.txt
  packages/tobot_engine/src/CMakeLists.txt
  packages/tobot_engine/src/Doxyfile
  packages/tobot_engine/src/core/asset_manager.cpp
  packages/tobot_engine/src/core/asset_manager.h
  packages/tobot_engine/src/core/game_entity.cpp
  packages/tobot_engine/src/core/game_entity.h
  packages/tobot_engine/src/core/render_object.cpp
  packages/tobot_engine/src/core/render_object.h
  packages/tobot_engine/src/core/scene.cpp
  packages/tobot_engine/src/core/scene.h
  packages/tobot_engine/src/core/scene_manager.h
  packages/tobot_engine/src/core/tobot_application.cpp
  packages/tobot_engine/src/core/tobot_application.h
  packages/tobot_engine/src/entry_point.h
  packages/tobot_engine/src/include/tobot_engine.h
  packages/tobot_engine/src/main.dox
  packages/tobot_engine/src/math/dimension.h
  packages/tobot_engine/src/math/vector2d.h
  packages/tobot_engine/src/project_config.h.in
  packages/tobot_engine/src/utilities/concepts.h
  packages/tobot_engine/src/widget/text.h
  packages/tobot_engine/tests/CMakeLists.txt
  packages/tobot_engine/tests/main.cpp
  packages/tobot_engine/tests/math/vector2d_test.cpp
  packages/tobot_tooling/CMakeLists.txt
  packages/tobot_tooling/src/CMakeLists.txt
  packages/tobot_tooling/src/include/tobot_tooling.h
  packages/tobot_tooling/src/logger.cpp
  packages/tobot_tooling/src/logger.h
  packages/tobot_tooling/src/tobot_asserts.h
  scripts/docs.bat
  scripts/docs.sh
  scripts/format.bat
  src/CMakeLists.txt
  src/main.dox
Labels: enhancement, cmake, code-quality

#35 feat: Define assets for example
  example/CMakeLists.txt
  example/assets/inspirational_picture.png
  example/example.cpp
Labels: enhancement, cmake

#40 feat: Designated exit codes
  .gitignore
  packages/tobot_engine/src/CMakeLists.txt
  packages/tobot_engine/src/core/exitcode.cpp
  packages/tobot_engine/src/core/exitcode.h
  packages/tobot_engine/src/core/tobot_application.cpp
Labels: enhancement

#41 docs: New architecture design
  README.md
  assets/tobot_architecture.drawio
  assets/tobot_architecture.png
  assets/tobot_architecturev2.drawio.png
Labels: documentation, architecture

#46 feat: :zap: added testmacros
  example/example.cpp
  packages/tobot_engine/src/core/tobot_application.cpp
  packages/tobot_tooling/src/CMakeLists.txt
  packages/tobot_tooling/src/debug/tobot_asserts.h
  packages/tobot_tooling/src/include/tobot_tooling.h
  packages/tobot_tooling/src/logging/logger.cpp
  packages/tobot_tooling/src/logging/logger.h
  packages/tobot_tooling/src/test/tobot_test.h
Labels: enhancement

#47 feat: :technologist: Added math library
  .github/workflows/tests.yaml
  CMakeLists.txt
  example/CMakeLists.txt
  packages/CMakeLists.txt
  packages/tobot_engine/CMakeLists.txt
  packages/tobot_engine/src/CMakeLists.txt
  packages/tobot_engine/src/core/render_object.h
  packages/tobot_engine/src/core/tobot_application.h
  packages/tobot_engine/src/include/tobot_engine.h
  packages/tobot_engine/src/utilities/concepts.h
  packages/tobot_engine/tests/CMakeLists.txt
  packages/tobot_math/CMakeLists.txt
  packages/tobot_math/src/CMakeLists.txt
  packages/tobot_math/src/concepts.h
  packages/tobot_math/src/dimension.cpp
  packages/tobot_math/src/dimension.h
  packages/tobot_math/src/include/tobot_math.h
  packages/tobot_math/src/vector2d.cpp
  packages/tobot_math/src/vector2d.h
  packages/tobot_math/tests/CMakeLists.txt
  packages/tobot_math/tests/main.cpp
  packages/tobot_math/tests/vector2d_test.cpp
Labels: enhancement, architecture

#48 feat: ⚡ added designated test example
  example/CMakeLists.txt
  example/src/CMakeLists.txt
  example/src/example.cpp
  example/test/CMakeLists.txt
  example/test/example.cpp
  packages/tobot_tooling/README.md
  packages/tobot_tooling/src/include/tobot_tooling.h
  packages/tobot_tooling/src/logging/logger.cpp
  packages/tobot_tooling/src/logging/logger.h
  packages/tobot_tooling/src/test/tobot_test.h
Labels: enhancement

#49 feat: Renamed tobot_engine to core
  .github/workflows/build.yaml
  CMakeLists.txt
  assets/Test_Framework_Architecture.drawio
  assets/Test_Framework_Architecture.png
  example/src/CMakeLists.txt
  example/test/CMakeLists.txt
  packages/CMakeLists.txt
  packages/tobot_core/CMakeLists.txt
  packages/tobot_core/README.md
  packages/tobot_core/src/CMakeLists.txt
  packages/tobot_core/src/Doxyfile
  packages/tobot_core/src/asset_manager.cpp
  packages/tobot_core/src/asset_manager.h
  packages/tobot_core/src/concepts.h
  packages/tobot_core/src/entry_point.h
  packages/tobot_core/src/exitcode.cpp
  packages/tobot_core/src/exitcode.h
  packages/tobot_core/src/game_entity.cpp
  packages/tobot_core/src/game_entity.h
  packages/tobot_core/src/include/tobot_engine.h
  packages/tobot_core/src/main.dox
  packages/tobot_core/src/project_config.h.in
  packages/tobot_core/src/render_object.cpp
  packages/tobot_core/src/render_object.h
  packages/tobot_core/src/scene.cpp
  packages/tobot_core/src/scene.h
  packages/tobot_core/src/scene_manager.h
  packages/tobot_core/src/tobot_application.cpp
  packages/tobot_core/src/tobot_application.h
  packages/tobot_engine/src/include/tobot_engine.h
  packages/tobot_engine/src/widget/text.h
  packages/tobot_math/README.md
  packages/tobot_math/src/CMakeLists.txt
  packages/tobot_math/src/DoxyFile
  packages/tobot_math/src/main.dox
  packages/tobot_tooling/README.md
  packages/tobot_tooling/src/CMakeLists.txt
  packages/tobot_tooling/src/Doxyfile
  packages/tobot_tooling/src/debug/tobot_asserts.h
  packages/tobot_tooling/src/main.dox
  scripts/docs.bat
  scripts/docs_core.bat
  scripts/docs_core.sh
  scripts/docs_math.bat
  scripts/docs_math.sh
  scripts/docs_tooling.bat
  scripts/docs_tooling.sh
  scripts/format.bat
Labels: documentation, cmake, architecture

#57 feat: added test sceleton
  README.md
  example/test/example.cpp
  packages/tobot_tooling/src/CMakeLists.txt
  packages/tobot_tooling/src/include/tobot_tooling.h
  packages/tobot_tooling/src/test/console_test_report_processor.cpp
  packages/tobot_tooling/src/test/console_test_report_processor.h
  packages/tobot_tooling/src/test/test_case.cpp
  packages/tobot_tooling/src/test/test_case.h
  packages/tobot_tooling/src/test/test_fixture.cpp
  packages/tobot_tooling/src/test/test_fixture.h
  packages/tobot_tooling/src/test/test_macros.h
  packages/tobot_tooling/src/test/test_report.cpp
  packages/tobot_tooling/src/test/test_report.h
  packages/tobot_tooling/src/test/test_report_processor.cpp
  packages/tobot_tooling/src/test/test_report_processor.h
  packages/tobot_tooling/src/test/test_runner.cpp
  packages/tobot_tooling/src/test/test_runner.h
  packages/tobot_tooling/src/test/test_state.cpp
  packages/tobot_tooling/src/test/test_state.h
  packages/tobot_tooling/src/test/tobot_test.h
  scripts/delete_logs.bat
  scripts/docs.bat
  scripts/docs_all.bat
  scripts/format.bat
Labels: enhancement

#59 feat: :building_construction: added dedicated testing library
  .github/workflows/build.yaml
  .github/workflows/codeql.yaml
  .github/workflows/tests.yaml
  CMakeLists.txt
  example/test/CMakeLists.txt
  example/test/example.cpp
  packages/CMakeLists.txt
  packages/tobot_test/CMakeLists.txt
  packages/tobot_test/README.md
  packages/tobot_test/src/CMakeLists.txt
  packages/tobot_test/src/console_test_report_processor.cpp
  packages/tobot_test/src/console_test_report_processor.h
  packages/tobot_test/src/include/tobot_test.h
  packages/tobot_test/src/test_case.cpp
  packages/tobot_test/src/test_case.h
  packages/tobot_test/src/test_fixture.cpp
  packages/tobot_test/src/test_fixture.h
  packages/tobot_test/src/test_macros.h
  packages/tobot_test/src/test_report.cpp
  packages/tobot_test/src/test_report.h
  packages/tobot_test/src/test_report_processor.cpp
  packages/tobot_test/src/test_report_processor.h
  packages/tobot_test/src/test_runner.cpp
  packages/tobot_test/src/test_runner.h
  packages/tobot_test/src/test_state.cpp
  packages/tobot_test/src/test_state.h
  packages/tobot_test/test/CMakeLists.txt
  packages/tobot_test/test/main.cpp
  packages/tobot_test/test/test_state_test.cpp
  packages/tobot_tooling/README.md
  packages/tobot_tooling/src/CMakeLists.txt
  packages/tobot_tooling/src/include/tobot_tooling.h
  packages/tobot_tooling/src/logging/logger.cpp
  packages/tobot_tooling/src/logging/logger.h
  packages/tobot_tooling/src/test/tobot_test.h
Labels: enhancement, test
